sudo: false
language: node_js
install:
  - yarn
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
    - github-pages
script:
  - npm run export # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: github-pages
  local-dir: public